### ISSUE TITLE
http://calendar.madeincincy.com/sources/import

### ISSUE THREAD

**Issue by ryw** [qcmerge/citizenry#6]
trying to import feed from http://www.meetup.com/OpenHack-Cincinnati/events/calendar/

get error 'ERROR: Unable to import: Unknown error: Validation failed: Title can't be blank'
## 

I've been trying to promote madeincincy.com a bit. We need a good portal like it.

It would be good to crack open this project @ OpenHack... looks like Citizenry has 30 open issues; we can get involved in maintaining that project too.

Thoughts @cdmwebs @mguterl ?

**Comment by cdmwebs** [comment]
It's a little scary in there, but it might make sense. There's a google group, too.

As for this particular issue, I'm not sure why that's happening. It's failing on existing feeds, too.
